# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bisectoin_res.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(851, 437)
        Form.setStyleSheet("QWidget{\n"
"    border-radius: 5px;\n"
"    background-color: #fff;\n"
"}\n"
"#res_table QHeaderView, #res_table{\n"
"    border: 0px;\n"
"    background-color: #fff;\n"
"    border-radius: 5px;\n"
"    text-align: left;\n"
"}\n"
"#res_table QHeaderView::section{\n"
"    border-radius: 0px;\n"
"    border-bottom: 1px solid #353535;\n"
"    border-top: 1px solid #353535;\n"
"    padding-left: 10px;\n"
"}\n"
"#res_table QHeaderView::item:selected{\n"
"    background-color:55aaff;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.res_table = QtWidgets.QTableWidget(Form)
        self.res_table.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.res_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.res_table.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.res_table.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.res_table.setGridStyle(QtCore.Qt.SolidLine)
        self.res_table.setObjectName("res_table")
        self.res_table.setColumnCount(8)
        self.res_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.res_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.res_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.res_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.res_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.res_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.res_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.res_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.res_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.res_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.res_table.setItem(0, 0, item)
        self.res_table.horizontalHeader().setCascadingSectionResizes(False)
        self.gridLayout.addWidget(self.res_table, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.res_table.setSortingEnabled(False)
        item = self.res_table.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.res_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "i"))
        item = self.res_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "xl"))
        item = self.res_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "f(xl)"))
        item = self.res_table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "xu"))
        item = self.res_table.horizontalHeaderItem(4)
        item.setText(_translate("Form", "f(xu)"))
        item = self.res_table.horizontalHeaderItem(5)
        item.setText(_translate("Form", "xr"))
        item = self.res_table.horizontalHeaderItem(6)
        item.setText(_translate("Form", "f(xr)"))
        item = self.res_table.horizontalHeaderItem(7)
        item.setText(_translate("Form", "e"))
        __sortingEnabled = self.res_table.isSortingEnabled()
        self.res_table.setSortingEnabled(False)
        item = self.res_table.item(0, 0)
        item.setText(_translate("Form", "hello"))
        self.res_table.setSortingEnabled(__sortingEnabled)
