# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guess.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_guess(object):
    def setupUi(self, guess):
        guess.setObjectName("guess")
        guess.resize(1080, 456)
        guess.setMinimumSize(QtCore.QSize(1080, 450))
        guess.setStyleSheet("#guess{\n"
"    background-image: url(:/imgs/imgs/WhatsApp Image 2023-05-11 at 14.12.52.jpg);\n"
"}\n"
"#widget, #r_editor, #l_editor, #res_editor{\n"
"    background-image: url(:/imgs/imgs/WhatsApp Image 2023-05-11 at 14.12.52.jpg);\n"
"    color: rgba(255, 255, 255, 180);\n"
"}\n"
"QLabel{\n"
"    color: rgba(255, 255, 255, 180)\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(guess)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(guess)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.rb_lbl = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(80)
        self.rb_lbl.setFont(font)
        self.rb_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.rb_lbl.setObjectName("rb_lbl")
        self.gridLayout_6.addWidget(self.rb_lbl, 1, 2, 1, 1)
        self.l_editor = QtWidgets.QTextBrowser(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.l_editor.setFont(font)
        self.l_editor.setObjectName("l_editor")
        self.gridLayout_6.addWidget(self.l_editor, 0, 1, 2, 1)
        self.rt_lbl = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(80)
        self.rt_lbl.setFont(font)
        self.rt_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.rt_lbl.setObjectName("rt_lbl")
        self.gridLayout_6.addWidget(self.rt_lbl, 0, 2, 1, 1)
        self.lt_lbl = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(80)
        self.lt_lbl.setFont(font)
        self.lt_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.lt_lbl.setObjectName("lt_lbl")
        self.gridLayout_6.addWidget(self.lt_lbl, 0, 0, 1, 1)
        self.lb_lbl = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(80)
        self.lb_lbl.setFont(font)
        self.lb_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.lb_lbl.setObjectName("lb_lbl")
        self.gridLayout_6.addWidget(self.lb_lbl, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.r_editor = QtWidgets.QTextBrowser(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.r_editor.setFont(font)
        self.r_editor.setObjectName("r_editor")
        self.gridLayout_3.addWidget(self.r_editor, 1, 2, 2, 1)
        self.lb_lbl_2 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(80)
        self.lb_lbl_2.setFont(font)
        self.lb_lbl_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.lb_lbl_2.setObjectName("lb_lbl_2")
        self.gridLayout_3.addWidget(self.lb_lbl_2, 2, 1, 1, 1)
        self.rt_lbl_2 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(80)
        self.rt_lbl_2.setFont(font)
        self.rt_lbl_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.rt_lbl_2.setObjectName("rt_lbl_2")
        self.gridLayout_3.addWidget(self.rt_lbl_2, 1, 3, 1, 1)
        self.lt_lbl_2 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(80)
        self.lt_lbl_2.setFont(font)
        self.lt_lbl_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.lt_lbl_2.setObjectName("lt_lbl_2")
        self.gridLayout_3.addWidget(self.lt_lbl_2, 1, 1, 1, 1)
        self.rb_lbl_2 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(80)
        self.rb_lbl_2.setFont(font)
        self.rb_lbl_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.rb_lbl_2.setObjectName("rb_lbl_2")
        self.gridLayout_3.addWidget(self.rb_lbl_2, 2, 3, 1, 1)
        self.horizontalLayout.addWidget(self.widget_3)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 53, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.res_editor = QtWidgets.QTextBrowser(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.res_editor.setFont(font)
        self.res_editor.setObjectName("res_editor")
        self.gridLayout_2.addWidget(self.res_editor, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(guess)
        QtCore.QMetaObject.connectSlotsByName(guess)

    def retranslateUi(self, guess):
        _translate = QtCore.QCoreApplication.translate
        guess.setWindowTitle(_translate("guess", "Form"))
        self.rb_lbl.setText(_translate("guess", "]"))
        self.l_editor.setHtml(_translate("guess", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.rt_lbl.setText(_translate("guess", "]"))
        self.lt_lbl.setText(_translate("guess", "["))
        self.lb_lbl.setText(_translate("guess", "["))
        self.r_editor.setHtml(_translate("guess", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.lb_lbl_2.setText(_translate("guess", "["))
        self.rt_lbl_2.setText(_translate("guess", "]"))
        self.lt_lbl_2.setText(_translate("guess", "["))
        self.rb_lbl_2.setText(_translate("guess", "]"))
        self.res_editor.setHtml(_translate("guess", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
import resources


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    guess = QtWidgets.QWidget()
    ui = Ui_guess()
    ui.setupUi(guess)
    guess.show()
    sys.exit(app.exec_())
